---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myappsecret
  namespace: srens
spec:
  encryptedData:
    PASSWORD: AgAguITr5qt9vpYL0dLqkj9G+CmOxXkdBpzkClvUT3sUv6MvAQgB0eg5DYW5wlUnnQ54r/F1DIVg62YsjI1sEVlldMGGIvj6MrGGpOBNjXmgId8azC0SWPXTWfTlKEa4n18oRjCRe3zYQ1pNPB7zLJmXxlBA52nRz8XmeU5VFlKpdOcGM7y2sYowoOjWIzlEGb1Z3Rp6yB/FnBHANpKspesmmzE5LV3kYeP2oQiknwVgheE+B2h99qc3amkFjfiAebyLNZl6g2l+vhYRqp+cDCQYFL9OOEpOD+gekPlDUiH5vMP3jjeA5rJi4SAVBoIIFxO8cybN10TZqMFtynq3mEYNhbHkLsT9CuFLFsxe4mWPo3eNQ9Ie5tSf4jZu6G/SjZvsCVxOH1ItavHz3hOfg5wRjVTxfFhHSCq53syuFjolaCYpes5b4NEpGKmxzZq+8j1Xb3FUc6vQkYivKjlnSGrmmxSgRQkcsZBCoL1jyRG/Ew9DF4QvO5py68h6ANpgKH2mgYLCNkajyGl5oH0eynRnw2UEwJw/47T3/twxv9FpVVdzMSy+NRy/I3VHAejV8/88RmCSMxGi3BLauEodE9VUk0xZfAnxqd99TKTFPWDopuIjfxnbzRtkh1oSlmR49ewBjx5zL7LI0RLdwSdsNX8NlAp8JBMRZjhzGYC4DXSESND+c/wZib3KyYN0S6bw8ht9DzbaL1O2nKn0
  template:
    metadata:
      creationTimestamp: null
      name: myappsecret
      namespace: srens
